#!/bin/bash

#BASE=http://oai.driver.research-infrastructures.eu/
#BASE=http://node1.integration.driver.research-infrastructures.eu:8280/is/mvc/oai/oai.do
BASE=http://zaguan.unizar.es/oai2d
MDFORMAT=oai_dc
SET=
DELAY=10

###############################

listRecordsCommand() {
 TOKEN=$1
 if [ -z "$TOKEN" ]; then
	 echo "$BASE?verb=ListRecords&metadataPrefix=$MDFORMAT"
 else
	 echo "$BASE?verb=ListRecords&resumptionToken=$TOKEN"
 fi
}

COUNT=0
TOKEN=""
while true; do
	echo "fetching token: $TOKEN"
	TOKEN=$(wget -q -O- $(listRecordsCommand $TOKEN) | grep resumptionToken | sed 's/.*>\(.*\)<.*/\1/')
	echo "sleeping $DELAY"
	sleep $DELAY
	if [ -z "$TOKEN" ]; then
		echo "no more pages"
		break
	fi
	COUNT=$((COUNT + 1))
done

echo "Fetched $COUNT pages"
